"""Sprite configuration constants — generated by spec agent.

Centralized constants module for all sprite specification data extracted from the
Chunky Kawaii style guide (README.md). No pygame imports — pure constants only (DR-001).

Usage:
    from src.sprite_config import PALETTE, OUTLINE_COLOR, SPRITE_SPECS
    color = PALETTE["primary_pink"]
    spec = SPRITE_SPECS["team1_cell"]
"""

# CHANGELOG: Sprint 3, Task 1 — Sprite configuration constants: 22 SPRITE_SPECS entries, 7-color PALETTE, group lists, SCENE_COLORS

from __future__ import annotations

# —— Palette ——————————————————————————————————————————————————————————————————————————

PALETTE: dict[str, tuple[int, int, int, int]] = {
    "primary_pink": (255, 181, 194, 255),   # #FFB5C2 — Team 1 (Kittens) base
    "mint_accent": (181, 234, 215, 255),    # #B5EAD7 — Team 2 (Puppies) base
    "lavender": (199, 206, 234, 255),       # #C7CEEA — Coach base
    "peach": (255, 218, 193, 255),          # #FFDAC1 — Warm skin/fur tone
    "sky_blue": (181, 216, 235, 255),       # #B5D8EB — Game background base
    "butter": (255, 245, 186, 255),         # #FFF5BA — Speech bubbles, stars
    "periwinkle": (168, 208, 230, 255),     # #A8D0E6 — Board frame, buttons
}

# —— Outline —————————————————————————————————————————————————————————————————————————

OUTLINE_COLOR: tuple[int, int, int, int] = (90, 74, 92, 255)  # #5A4A5C
OUTLINE_WIDTH: int = 4

# —— Sprite Specifications ——————————————————————————————————————————————————————————

SPRITE_SPECS: dict[str, dict[str, object]] = {
    # —— Team 1: Kittens ——————————————————————————————————————————————————————
    "team1_cell": {
        "width": 120,
        "height": 120,
        "base_color": "primary_pink",
        "description": "Kitten board-cell sprite (sitting pose)",
    },
    "team1_wiggle": {
        "width": 120,
        "height": 120,
        "base_color": "primary_pink",
        "description": "Kitten idle animation frame (ear wiggle)",
    },
    "team1_celebrate": {
        "width": 120,
        "height": 120,
        "base_color": "primary_pink",
        "description": "Kitten win celebration pose (paws up)",
    },
    # —— Team 2: Puppies ——————————————————————————————————————————————————————
    "team2_cell": {
        "width": 120,
        "height": 120,
        "base_color": "mint_accent",
        "description": "Puppy board-cell sprite (sitting pose)",
    },
    "team2_wiggle": {
        "width": 120,
        "height": 120,
        "base_color": "mint_accent",
        "description": "Puppy idle animation frame (tail wag)",
    },
    "team2_celebrate": {
        "width": 120,
        "height": 120,
        "base_color": "mint_accent",
        "description": "Puppy win celebration pose (play bow)",
    },
    # —— Coach ————————————————————————————————————————————————————————————————
    "coach_wave": {
        "width": 200,
        "height": 200,
        "base_color": "lavender",
        "description": "Coach greeting/wave expression",
    },
    "coach_point": {
        "width": 200,
        "height": 200,
        "base_color": "lavender",
        "description": "Coach thinking/pointing expression",
    },
    "coach_cheer_small": {
        "width": 200,
        "height": 200,
        "base_color": "lavender",
        "description": "Coach encouragement expression",
    },
    "coach_cheer": {
        "width": 200,
        "height": 200,
        "base_color": "lavender",
        "description": "Coach big celebration expression",
    },
    "coach_aww": {
        "width": 200,
        "height": 200,
        "base_color": "lavender",
        "description": "Coach consoling/aww expression",
    },
    "coach_idle": {
        "width": 200,
        "height": 200,
        "base_color": "lavender",
        "description": "Coach neutral/idle expression",
    },
    # —— Scene Backgrounds ————————————————————————————————————————————————————
    "bg_team_select": {
        "width": 960,
        "height": 720,
        "base_color": "lavender",
        "description": "Team Select background (full window, Lavender dominant)",
    },
    "bg_game": {
        "width": 960,
        "height": 720,
        "base_color": "sky_blue",
        "description": "Game scene background (full window, Sky Blue dominant)",
    },
    "bg_celebration": {
        "width": 960,
        "height": 720,
        "base_color": "primary_pink",
        "description": "Celebration scene background (full window, Pink dominant)",
    },
    # —— Effects ———————————————————————————————————————————————————————————————
    "sparkle": {
        "width": 32,
        "height": 32,
        "base_color": "periwinkle",
        "description": "Sparkle particle (4-point star, rounded tips)",
    },
    "confetti": {
        "width": 16,
        "height": 16,
        "base_color": "butter",
        "description": "Confetti particle (rounded rectangle)",
    },
    "heart": {
        "width": 24,
        "height": 24,
        "base_color": "primary_pink",
        "description": "Extra delight heart shape",
    },
    "star": {
        "width": 24,
        "height": 24,
        "base_color": "butter",
        "description": "Extra delight star shape",
    },
    # —— UI Chrome ————————————————————————————————————————————————————————————
    "btn_start": {
        "width": 200,
        "height": 60,
        "base_color": "periwinkle",
        "description": "Play/Start pill-shaped button",
    },
    "btn_play_again": {
        "width": 200,
        "height": 60,
        "base_color": "primary_pink",
        "description": "Play Again pill-shaped button",
    },
    "board_frame": {
        "width": 440,
        "height": 440,
        "base_color": "periwinkle",
        "description": "On-theme board border (garden fence with rounded pickets)",
    },
}

# —— Asset Group Lists ——————————————————————————————————————————————————————————

TEAM_KEYS: list[str] = [
    "team1_cell",
    "team1_wiggle",
    "team1_celebrate",
    "team2_cell",
    "team2_wiggle",
    "team2_celebrate",
]

COACH_KEYS: list[str] = [
    "coach_wave",
    "coach_point",
    "coach_cheer_small",
    "coach_cheer",
    "coach_aww",
    "coach_idle",
]

BACKGROUND_KEYS: list[str] = [
    "bg_team_select",
    "bg_game",
    "bg_celebration",
]

EFFECT_KEYS: list[str] = [
    "sparkle",
    "confetti",
    "heart",
    "star",
]

UI_KEYS: list[str] = [
    "btn_start",
    "btn_play_again",
    "board_frame",
]

# —— Scene Color Mappings ———————————————————————————————————————————————————————

SCENE_COLORS: dict[str, list[str]] = {
    "team_select": ["lavender", "butter", "periwinkle"],
    "game": ["sky_blue", "mint_accent", "peach"],
    "celebration": ["primary_pink", "butter", "lavender"],
}